title: Joe Ledger
description: My Professional Website
author: Joe Ledger
logo: static/img/avatar.png
github: https://github.com/joewledger
about: Software Engineer & Researcher

baseurl: ""
url: ""

disqus_shortname: joeledger
google_analytics: UA-72862926-1


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
